---

- hosts: all
  become: true
  tasks:

  - name: update repository cache
    apt:
      update_cache: yes

  - name: install apache2 packages
    apt:
      name: apache2
      state: latest

  - name: add php supporting for apache
    apt:
      name: libapache2-mod-php
      state: latest
