---

- hosts: all
  become: true
  tasks:

  - name: remove apache2 packages
    apt:
      name: apache2
      state: absent

  - name: remove php supporting for apache
    apt:
      name: libapache2-mod-php
      state: absent
