---

- hosts: all
  become: true
  tasks:

  - name: update repo cache (AlmaLinux)
    tags: alway
    dnf:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "AlmaLinux"

  - name: install updates (Ubuntu)
    tags: alway
    apt:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "Ubuntu"

- hosts: all
  become: true
  roles:
    - base
    
- hosts: web_servers
  become: true
  roles:
    - web_servers
 
- hosts: db_servers
  become: true
  roles:
    - db_servers
 
- hosts: file_servers
  become: true
  roles:
    - file_servers